version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - /local/repository:/root/.ollama
      - /data:/data
    networks:
      - app-network

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge